language: node_js
node_js:
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
os: "linux"
dist: "xenial"
jobs:
  include:
    - stage: test
      install: npm install
      script: npm run test
    - stage: coverage
      node_js: 12.16
      install: npm install && npm install -g codecov
      script: npm run test && codecov
